_target_: lightning.pytorch.trainer.Trainer

default_root_dir: ${paths.pretrained_encoder_dir}

min_epochs: 1 # prevents early stopping
max_epochs: 150

accelerator: gpu
devices: 1

enable_model_summary: 
profiler: simple

# mixed precision for extra speed-up
precision: 16

# perform a validation loop every N training epochs
check_val_every_n_epoch: 1

# set True to to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: True
