_target_: src.models.mnist_module.ACAModule

net:
  _target_: src.models.components.autoencoder.AutoEncoder
  in_features: 2048
  code_features: 64
  activation: nn.ReLU

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

