defaults:
  - model_checkpoint.yaml
  - early_stopping.yaml
  - model_summary.yaml
  - rich_progress_bar.yaml
  - _self_

model_checkpoint:
  monitor: "val/AUROC"
  mode: "max"
  save_top_k: 1
  verbose: True
  save_last: True

early_stopping:
  monitor: "val/AUROC"
  patience: 10
  verbose: True
  mode: "max"

model_summary:
  max_depth: -1
