defaults:
  - model_checkpoint.yaml
  - early_stopping.yaml
  - model_summary.yaml
  - rich_progress_bar.yaml
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  monitor: "val/loss"
  mode: "min"
  save_top_k: 1
  verbose: True
  save_last: True

early_stopping:
  monitor: "val/loss"
  patience: 10
  verbose: True
  mode: "min"

model_summary:
  max_depth: -1
