_target_: src.models.encoding_module.ACAModule

task: ${task_type}

net:
  _target_: src.models.components.encoders.HalfStepSimSiam
  in_features: ${feature_length}
  code_features: 256
  dropout: 0.2
  norm_layer: true
  similarity_function: dot_product
  layer_activation: 
    _target_: torch.nn.ReLU

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: ${metric_direction}
  factor: 0.1
  patience: 10

criterion:
  _target_: src.models.components.losses.SimSiamLoss

input_type: pair