# @package _global_

defaults:
  - _self_
  - data: null # must be specified in experiment config
  - model: null ## see above
  - logger: wandb
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ???