## Use this as a template for your own config files
defaults:
  - _self_
  - data: test_Concat512ECFP2MixedACNet.yaml
  #- debug: default.yaml
  - extras: default.yaml
  - model: test_JointAutoEncoder.yaml
  - callbacks: default.yaml
  - logger: wandb.yaml
  - paths: default.yaml
  - trainer: default.yaml
  - wandb: cmvcordova.yaml
  - hydra: default.yaml
  
tags: ["dev"]

# set False to skip model training
train: True

# evaluate on test set, using best model weights achieved during training
# lightning chooses best weights based on the metric specified in checkpoint callback
test: True

# compile model for faster training with pytorch 2.0
compile: True

# simply provide checkpoint path to resume training
ckpt_path: null

# seed for random number generators in pytorch, numpy and python.random
seed: 42